name: CD-ApiMDeveloperPortal-Migration-Pipeline

trigger: none

jobs:

  # All tasks on APIM Developer portal pipeline
  - job: Migrate_APIM_Developer_Portal
    displayName: Migrate APIM Developer portal from one APIM instance to another APIM instance Migration 
    timeoutInMinutes: 90
    steps:
      - task: Npm@1
        displayName: Npm Install command
        inputs:
          command: "install"

      - pwsh: |        
          node ./migrate --sourceSubscriptionId "$(sourceSubscriptionId)" --sourceResourceGroupName  "$(sourceResourceGroupName)" --sourceServiceName "$(sourceServiceName)" --destServiceName "$(destinationServiceName)" --destSubscriptionId "$(destSubscriptionId)" --destResourceGroupName "$(destResourceGroupName)"  --sourceServicePrincipal "$(sourceServicePrincipal)" --sourceSecret "$(sourceServicePrincipalSecret)"  --destTenantId "$(destAzureTenantId)" --destServicePrincipal "$(destServicePrincipal)" --destSecret "$(destServicePrincipalSecret)"
        workingDirectory: "$(System.DefaultWorkingDirectory)/scripts.v3"
        displayName: Run Migrate cmd from $(sourceServiceName) to $(destinationServiceName)  
        env:
          AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
              
      - pwsh: |
          node ./updatecontenturl --existingEnvUrls "$(existingEnvUrls)" --destEnvUrls  "$(destEnvUrls)" --destServiceName "$(destinationServiceName)" --destSubscriptionId "$(destSubscriptionId)" --destResourceGroupName "$(destResourceGroupName)"
        workingDirectory: '$(System.DefaultWorkingDirectory)/scripts.v3'
        displayName: Update urls for  $(destinationServiceName)
        env:
          AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
